language: node_js
node_js:
    - "node"
cache:
  directories:
    - ~/npm_cache
sudo: false
install:
    - npm config set prefer-offline true
    - npm set cache ~/npm_cache
    - npm install -g enactjs/cli#develop
    - npm install
script:
    - enact lint --strict
    - npm run pack

