language: node_js
node_js:
    - "node"
cache:
  directories:
    - ~/.npm
sudo: false
install:
    - npm 
    - npm install -g enactjs/cli#develop
    - npm install
script:
    - enact lint --strict
    - npm run pack

